baseurl = "https://stevehsiao.com/"
defaultContentLanguage = "zh-tw"
locale = "zh-tw"
title = "Ahsiao's Blog"
theme = "somestyleplease"
enableEmoji = true
ignoreErrors = ["additional-script-loading-error"]

[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark.renderer]
    unsafe = true
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4
    ordered = false

[params]
  sitename = "Ahsiao's Blog"
  defaultColor = "auto"
  description = ""
  mainSections = ['posts']
  toc = true
  tocOpen = false
  goToTop = true
  dateFormat = "2006年01月02日"
  rssFeedDescription = "summary"
  siteStartYear = 2016
  noDefaultSummaryCover = true
  author = "ggd"

[[params.socialIcons]]
name = "github"
url = "https://github.com/ggd"

[[params.socialIcons]]
name = "Rss"
url = "/index.xml"
[caches]
  [caches.images]
    dir = ':cacheDir/images'

